# Makefile
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = C:\Users\orucc\Desktop\Coding_Projects\Kasirga_Ates_Teknofest\Teknofest-Ates-Processor-Design\KasirgaVerilogCopy\KasirgaVerilogCopy.srcs\sources_1\new\ArithmeticLogicUnit.v
TOPLEVEL = ArithmeticLogicUnit
MODULE = alu_test
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim